import { createClient } from "@/lib/supabase/server";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import {
  requireApiRole,
  ApiError,
  successResponse,
} from "@/lib/api/auth";
import {
  validateDeliveryTransition,
  DeliveryStatus,
} from "@/lib/purchasing/delivery";

// ============================================================
// POST /api/purchasing/delivery/:id/arrive
// Transitions: IN_TRANSIT → DELIVERED
// Also creates GRN automatically
// ============================================================

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await requireApiRole(["purchasing_admin", "purchasing_staff", "warehouse_staff"]);
    const supabase = await createClient();
    const { id } = await params;

    const body = await request.json().catch(() => ({}));
    const notes = body.notes as string | undefined;

    // Get current delivery
    const { data: delivery, error: fetchError } = await supabase
      .from("deliveries")
      .select("*, purchase_order:purchase_order_id(id, po_number, status, supplier_id)")
      .eq("id", id)
      .single();

    if (fetchError || !delivery) {
      throw ApiError.notFound("Delivery tidak ditemukan");
    }

    // Validate transition
    try {
      validateDeliveryTransition(delivery.status as DeliveryStatus, "delivered");
    } catch (e) {
      throw ApiError.badRequest((e as Error).message);
    }

    const arrivedAt = new Date().toISOString();

    // Use a transaction: update delivery + create GRN
    // Since Supabase JS doesn't have native transaction, we do sequential with error handling
    const { data: updatedDelivery, error: deliveryError } = await supabase
      .from("deliveries")
      .update({
        status: "delivered",
        tanggal_aktual_tiba: arrivedAt.split("T")[0],
        updated_by: user.id,
      })
      .eq("id", id)
      .select()
      .single();

    if (deliveryError) throw deliveryError;

    // Create GRN (Goods Receipt) — nomor_gr auto-generated by DB trigger
    const { data: grn, error: grnError } = await supabase
      .from("goods_receipts")
      .insert({
        purchase_order_id: delivery.purchase_order_id,
        delivery_id: id,
        tanggal_terima: arrivedAt.split("T")[0],
        penerima_id: user.id,
        status: "pending",
        catatan: notes || null,
        created_by: user.id,
      })
      .select(
        `
        *,
        purchase_order:purchase_order_id(id, po_number, status)
      `
      )
      .single();

    if (grnError) {
      // Rollback delivery status
      await supabase
        .from("deliveries")
        .update({ status: "in_transit", updated_by: user.id })
        .eq("id", id);
      throw new Error(`Failed to create GRN: ${grnError.message}`);
    }

    return successResponse(
      { delivery: updatedDelivery, grn },
      `Barang arrived — GRN ${grn.nomor_gr} berhasil dibuat`
    );
  } catch (error) {
    if (error instanceof ApiError) return error.toResponse();
    console.error("Error marking delivery as arrived:", error);
    return ApiError.server("Failed to mark delivery as arrived").toResponse();
  }
}
